### ISSUE TITLE
Instance label

### ISSUE THREAD

**Issue by iris0329** [pqhieu/jsis3d#5]
Hi, 
Could you please tell me, how to get the instance label, Are you manually tagged?
Thanks !

**Comment by pqhieu** [comment]
Please check these dataset [SceneNN](http://scenenn.net), [S3DIS](http://buildingparser.stanford.edu/dataset.html), and [ScanNet](http://www.scan-net.org). The short answer is yes, the instance labels are manually annotated.

I will close this issue because it doesn't relate to the code. If you have further questions related to the paper, please send me an email.

**Comment by jediofgever** [comment]
if I want to do semantic segmentation instead of instance segmentation, can I just assign class label to the object that  I want to detect ?
